# Site settings
title: Portfolio de Ludovic Tresson
email: tresson@intechinfo.fr
description: > # this means to ignore newlines until "baseurl:"
  Bienvenue sur mon Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ludovict.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  LudovicT

# Build settings
markdown: kramdown
categories: [skill, path, project, personnal]
submenu: [true, false]
show_in_menu: [true, false]
username: Ludovic Tresson